const fs = require('fs');
const path = require('path');

// Função para traduzir texto de espanhol para português
function translateText(text) {
    if (!text || typeof text !== 'string') return '';
    
    const translations = {
        // Traduções básicas ES → PT
        'Sirena': 'Sirene',
        'Exterior': 'Exterior',
        'Interior': 'Interior',
        'Detector': 'Detetor',
        'Sensor': 'Sensor',
        'Alarma': 'Alarme',
        'Sistema': 'Sistema',
        'Inalámbrico': 'Sem fios',
        'Batería': 'Bateria',
        'Alimentación': 'Alimentação',
        'Instalación': 'Instalação',
        'Configuración': 'Configuração',
        'Aplicación': 'Aplicação',
        'Conexión': 'Ligação',
        'Comunicación': 'Comunicação',
        'Tecnología': 'Tecnologia',
        'Seguridad': 'Segurança',
        'Protección': 'Proteção',
        'Vigilancia': 'Vigilância',
        'Control': 'Controlo',
        'Monitoreo': 'Monitorização',
        'Notificación': 'Notificação',
        'Activación': 'Ativação',
        'Desactivación': 'Desativação',
        'Funcionamiento': 'Funcionamento',
        'Características': 'Características',
        'Especificaciones': 'Especificações',
        'Dimensiones': 'Dimensões',
        'Temperatura': 'Temperatura',
        'Humedad': 'Humidade',
        'Resistencia': 'Resistência',
        'Certificación': 'Certificação',
        'Garantía': 'Garantia',
        'Mantenimiento': 'Manutenção',
        'Reparación': 'Reparação',
        'Sustitución': 'Substituição',
        'Actualización': 'Atualização',
        'Versión': 'Versão',
        'Modelo': 'Modelo',
        'Referencia': 'Referência',
        'Código': 'Código',
        'Número': 'Número',
        'Serie': 'Série',
        'Fabricante': 'Fabricante',
        'Distribuidor': 'Distribuidor',
        'Proveedor': 'Fornecedor',
        'Cliente': 'Cliente',
        'Usuario': 'Utilizador',
        'Administrador': 'Administrador',
        'Técnico': 'Técnico',
        'Profesional': 'Profissional',
        'Doméstico': 'Doméstico',
        'Comercial': 'Comercial',
        'Industrial': 'Industrial',
        'Residencial': 'Residencial',
        'Oficina': 'Escritório',
        'Hogar': 'Casa',
        'Edificio': 'Edifício',
        'Vivienda': 'Habitação',
        'Local': 'Local',
        'Zona': 'Zona',
        'Área': 'Área',
        'Espacio': 'Espaço',
        'Lugar': 'Lugar',
        'Sitio': 'Sítio',
        'Ubicación': 'Localização',
        'Posición': 'Posição',
        'Colocación': 'Colocação',
        'Montaje': 'Montagem',
        'Fijación': 'Fixação',
        'Sujeción': 'Sujeição',
        'Soporte': 'Suporte',
        'Base': 'Base',
        'Estructura': 'Estrutura',
        'Marco': 'Moldura',
        'Carcasa': 'Caixa',
        'Cubierta': 'Cobertura',
        'Tapa': 'Tampa',
        'Panel': 'Painel',
        'Pantalla': 'Ecrã',
        'Display': 'Display',
        'Indicador': 'Indicador',
        'LED': 'LED',
        'Luz': 'Luz',
        'Iluminación': 'Iluminação',
        'Señal': 'Sinal',
        'Aviso': 'Aviso',
        'Alerta': 'Alerta',
        'Emergencia': 'Emergência',
        'Peligro': 'Perigo',
        'Riesgo': 'Risco',
        'Amenaza': 'Ameaça',
        'Intrusión': 'Intrusão',
        'Robo': 'Roubo',
        'Hurto': 'Furto',
        'Sabotaje': 'Sabotagem',
        'Vandalismo': 'Vandalismo',
        'Daño': 'Dano',
        'Deterioro': 'Deterioração',
        'Fallo': 'Falha',
        'Error': 'Erro',
        'Problema': 'Problema',
        'Solución': 'Solução',
        'Respuesta': 'Resposta',
        'Reacción': 'Reação',
        'Acción': 'Ação',
        'Medida': 'Medida',
        'Procedimiento': 'Procedimento',
        'Proceso': 'Processo',
        'Método': 'Método',
        'Técnica': 'Técnica',
        'Forma': 'Forma',
        'Manera': 'Maneira',
        'Modo': 'Modo',
        'Tipo': 'Tipo',
        'Clase': 'Classe',
        'Categoría': 'Categoria',
        'Grupo': 'Grupo',
        'Familia': 'Família',
        'Gama': 'Gama',
        'Línea': 'Linha',
        'Serie': 'Série',
        'Colección': 'Coleção',
        'Conjunto': 'Conjunto',
        'Kit': 'Kit',
        'Pack': 'Pack',
        'Lote': 'Lote',
        'Unidad': 'Unidade',
        'Pieza': 'Peça',
        'Componente': 'Componente',
        'Elemento': 'Elemento',
        'Parte': 'Parte',
        'Sección': 'Secção',
        'División': 'Divisão',
        'Departamento': 'Departamento',
        'Servicio': 'Serviço',
        'Atención': 'Atenção',
        'Soporte': 'Suporte',
        'Ayuda': 'Ajuda',
        'Asistencia': 'Assistência',
        'Consulta': 'Consulta',
        'Información': 'Informação',
        'Datos': 'Dados',
        'Detalles': 'Detalhes',
        'Descripción': 'Descrição',
        'Explicación': 'Explicação',
        'Instrucciones': 'Instruções',
        'Manual': 'Manual',
        'Guía': 'Guia',
        'Tutorial': 'Tutorial',
        'Curso': 'Curso',
        'Formación': 'Formação',
        'Capacitación': 'Capacitação',
        'Entrenamiento': 'Treino',
        'Práctica': 'Prática',
        'Experiencia': 'Experiência',
        'Conocimiento': 'Conhecimento',
        'Habilidad': 'Habilidade',
        'Destreza': 'Destreza',
        'Competencia': 'Competência',
        'Capacidad': 'Capacidade',
        'Potencia': 'Potência',
        'Fuerza': 'Força',
        'Energía': 'Energia',
        'Corriente': 'Corrente',
        'Voltaje': 'Voltagem',
        'Tensión': 'Tensão',
        'Frecuencia': 'Frequência',
        'Alcance': 'Alcance',
        'Distancia': 'Distância',
        'Radio': 'Raio',
        'Cobertura': 'Cobertura',
        'Rango': 'Gama',
        'Límite': 'Limite',
        'Máximo': 'Máximo',
        'Mínimo': 'Mínimo',
        'Óptimo': 'Ótimo',
        'Ideal': 'Ideal',
        'Perfecto': 'Perfeito',
        'Excelente': 'Excelente',
        'Bueno': 'Bom',
        'Regular': 'Regular',
        'Malo': 'Mau',
        'Deficiente': 'Deficiente',
        'Insuficiente': 'Insuficiente',
        'Adecuado': 'Adequado',
        'Apropiado': 'Apropriado',
        'Conveniente': 'Conveniente',
        'Útil': 'Útil',
        'Práctico': 'Prático',
        'Funcional': 'Funcional',
        'Eficaz': 'Eficaz',
        'Eficiente': 'Eficiente',
        'Efectivo': 'Efetivo',
        'Fiable': 'Fiável',
        'Confiable': 'Confiável',
        'Seguro': 'Seguro',
        'Estable': 'Estável',
        'Sólido': 'Sólido',
        'Robusto': 'Robusto',
        'Resistente': 'Resistente',
        'Duradero': 'Duradouro',
        'Permanente': 'Permanente',
        'Temporal': 'Temporal',
        'Provisional': 'Provisório',
        'Definitivo': 'Definitivo',
        'Final': 'Final',
        'Último': 'Último',
        'Primero': 'Primeiro',
        'Inicial': 'Inicial',
        'Original': 'Original',
        'Nuevo': 'Novo',
        'Reciente': 'Recente',
        'Actual': 'Atual',
        'Presente': 'Presente',
        'Futuro': 'Futuro',
        'Pasado': 'Passado',
        'Anterior': 'Anterior',
        'Siguiente': 'Seguinte',
        'Próximo': 'Próximo',
        'Cercano': 'Próximo',
        'Lejano': 'Distante',
        'Cerca': 'Perto',
        'Lejos': 'Longe',
        'Dentro': 'Dentro',
        'Fuera': 'Fora',
        'Arriba': 'Em cima',
        'Abajo': 'Em baixo',
        'Encima': 'Por cima',
        'Debajo': 'Por baixo',
        'Delante': 'À frente',
        'Detrás': 'Atrás',
        'Izquierda': 'Esquerda',
        'Derecha': 'Direita',
        'Centro': 'Centro',
        'Medio': 'Meio',
        'Lateral': 'Lateral',
        'Frontal': 'Frontal',
        'Trasero': 'Traseiro',
        'Superior': 'Superior',
        'Inferior': 'Inferior',
        'Horizontal': 'Horizontal',
        'Vertical': 'Vertical',
        'Diagonal': 'Diagonal',
        'Recto': 'Reto',
        'Curvo': 'Curvo',
        'Redondo': 'Redondo',
        'Circular': 'Circular',
        'Cuadrado': 'Quadrado',
        'Rectangular': 'Retangular',
        'Triangular': 'Triangular',
        'Ovalado': 'Oval',
        'Alargado': 'Alongado',
        'Estrecho': 'Estreito',
        'Ancho': 'Largo',
        'Grueso': 'Grosso',
        'Delgado': 'Fino',
        'Alto': 'Alto',
        'Bajo': 'Baixo',
        'Grande': 'Grande',
        'Pequeño': 'Pequeno',
        'Mediano': 'Médio',
        'Gigante': 'Gigante',
        'Enorme': 'Enorme',
        'Diminuto': 'Diminuto',
        'Microscópico': 'Microscópico',
        'Visible': 'Visível',
        'Invisible': 'Invisível',
        'Transparente': 'Transparente',
        'Opaco': 'Opaco',
        'Claro': 'Claro',
        'Oscuro': 'Escuro',
        'Brillante': 'Brilhante',
        'Mate': 'Mate',
        'Liso': 'Liso',
        'Rugoso': 'Rugoso',
        'Suave': 'Suave',
        'Áspero': 'Áspero',
        'Duro': 'Duro',
        'Blando': 'Mole',
        'Flexible': 'Flexível',
        'Rígido': 'Rígido',
        'Elástico': 'Elástico',
        'Plástico': 'Plástico',
        'Metálico': 'Metálico',
        'Madera': 'Madeira',
        'Cristal': 'Cristal',
        'Vidrio': 'Vidro',
        'Cerámica': 'Cerâmica',
        'Papel': 'Papel',
        'Cartón': 'Cartão',
        'Tela': 'Tecido',
        'Cuero': 'Couro',
        'Goma': 'Borracha',
        'Silicona': 'Silicone',
        'Aluminio': 'Alumínio',
        'Acero': 'Aço',
        'Hierro': 'Ferro',
        'Cobre': 'Cobre',
        'Oro': 'Ouro',
        'Plata': 'Prata',
        'Bronce': 'Bronze',
        'Titanio': 'Titânio',
        'Carbono': 'Carbono',
        'Fibra': 'Fibra',
        'Composite': 'Compósito',
        'Sintético': 'Sintético',
        'Natural': 'Natural',
        'Orgánico': 'Orgânico',
        'Inorgánico': 'Inorgânico',
        'Químico': 'Químico',
        'Físico': 'Físico',
        'Mecánico': 'Mecânico',
        'Eléctrico': 'Elétrico',
        'Electrónico': 'Eletrónico',
        'Digital': 'Digital',
        'Analógico': 'Analógico',
        'Automático': 'Automático',
        'Manual': 'Manual',
        'Remoto': 'Remoto',
        'Local': 'Local',
        'Centralizado': 'Centralizado',
        'Descentralizado': 'Descentralizado',
        'Distribuido': 'Distribuído',
        'Concentrado': 'Concentrado',
        'Disperso': 'Disperso',
        'Unificado': 'Unificado',
        'Separado': 'Separado',
        'Independiente': 'Independente',
        'Dependiente': 'Dependente',
        'Autónomo': 'Autónomo',
        'Conectado': 'Ligado',
        'Desconectado': 'Desligado',
        'Encendido': 'Ligado',
        'Apagado': 'Desligado',
        'Activado': 'Ativado',
        'Desactivado': 'Desativado',
        'Habilitado': 'Habilitado',
        'Deshabilitado': 'Desabilitado',
        'Disponible': 'Disponível',
        'No disponible': 'Não disponível',
        'Ocupado': 'Ocupado',
        'Libre': 'Livre',
        'Abierto': 'Aberto',
        'Cerrado': 'Fechado',
        'Bloqueado': 'Bloqueado',
        'Desbloqueado': 'Desbloqueado',
        'Protegido': 'Protegido',
        'Desprotegido': 'Desprotegido',
        'Cifrado': 'Cifrado',
        'Descifrado': 'Decifrado',
        'Codificado': 'Codificado',
        'Decodificado': 'Descodificado',
        'Comprimido': 'Comprimido',
        'Descomprimido': 'Descomprimido',
        'Compactado': 'Compactado',
        'Expandido': 'Expandido',
        'Reducido': 'Reduzido',
        'Ampliado': 'Ampliado',
        'Aumentado': 'Aumentado',
        'Disminuido': 'Diminuído',
        'Mejorado': 'Melhorado',
        'Empeorado': 'Piorado',
        'Optimizado': 'Otimizado',
        'Actualizado': 'Atualizado',
        'Obsoleto': 'Obsoleto',
        'Moderno': 'Moderno',
        'Antiguo': 'Antigo',
        'Clásico': 'Clássico',
        'Tradicional': 'Tradicional',
        'Innovador': 'Inovador',
        'Revolucionario': 'Revolucionário',
        'Avanzado': 'Avançado',
        'Básico': 'Básico',
        'Simple': 'Simples',
        'Complejo': 'Complexo',
        'Complicado': 'Complicado',
        'Fácil': 'Fácil',
        'Difícil': 'Difícil',
        'Sencillo': 'Simples',
        'Elaborado': 'Elaborado',
        'Detallado': 'Detalhado',
        'General': 'Geral',
        'Específico': 'Específico',
        'Particular': 'Particular',
        'Especial': 'Especial',
        'Normal': 'Normal',
        'Estándar': 'Padrão',
        'Personalizado': 'Personalizado',
        'Customizado': 'Personalizado',
        'Adaptado': 'Adaptado',
        'Modificado': 'Modificado',
        'Alterado': 'Alterado',
        'Cambiado': 'Mudado',
        'Transformado': 'Transformado',
        'Convertido': 'Convertido',
        'Traducido': 'Traduzido',
        'Interpretado': 'Interpretado',
        'Explicado': 'Explicado',
        'Aclarado': 'Esclarecido',
        'Definido': 'Definido',
        'Determinado': 'Determinado',
        'Establecido': 'Estabelecido',
        'Fijado': 'Fixado',
        'Configurado': 'Configurado',
        'Programado': 'Programado',
        'Planificado': 'Planeado',
        'Organizado': 'Organizado',
        'Estructurado': 'Estruturado',
        'Ordenado': 'Ordenado',
        'Clasificado': 'Classificado',
        'Categorizado': 'Categorizado',
        'Agrupado': 'Agrupado',
        'Dividido': 'Dividido',
        'Separado': 'Separado',
        'Unido': 'Unido',
        'Conectado': 'Ligado',
        'Enlazado': 'Ligado',
        'Vinculado': 'Vinculado',
        'Relacionado': 'Relacionado',
        'Asociado': 'Associado',
        'Combinado': 'Combinado',
        'Mezclado': 'Misturado',
        'Integrado': 'Integrado',
        'Incorporado': 'Incorporado',
        'Incluido': 'Incluído',
        'Contenido': 'Contido',
        'Comprendido': 'Compreendido',
        'Entendido': 'Entendido',
        'Conocido': 'Conhecido',
        'Reconocido': 'Reconhecido',
        'Identificado': 'Identificado',
        'Detectado': 'Detetado',
        'Descubierto': 'Descoberto',
        'Encontrado': 'Encontrado',
        'Localizado': 'Localizado',
        'Ubicado': 'Localizado',
        'Situado': 'Situado',
        'Colocado': 'Colocado',
        'Puesto': 'Posto',
        'Instalado': 'Instalado',
        'Montado': 'Montado',
        'Fijado': 'Fixado',
        'Sujetado': 'Sujeito',
        'Asegurado': 'Assegurado',
        'Garantizado': 'Garantido',
        'Certificado': 'Certificado',
        'Verificado': 'Verificado',
        'Comprobado': 'Comprovado',
        'Confirmado': 'Confirmado',
        'Validado': 'Validado',
        'Aprobado': 'Aprovado',
        'Autorizado': 'Autorizado',
        'Permitido': 'Permitido',
        'Prohibido': 'Proibido',
        'Restringido': 'Restrito',
        'Limitado': 'Limitado',
        'Controlado': 'Controlado',
        'Regulado': 'Regulado',
        'Supervisado': 'Supervisionado',
        'Monitoreado': 'Monitorizado',
        'Observado': 'Observado',
        'Vigilado': 'Vigiado',
        'Custodiado': 'Custodiado',
        'Protegido': 'Protegido',
        'Defendido': 'Defendido',
        'Resguardado': 'Resguardado',
        'Preservado': 'Preservado',
        'Conservado': 'Conservado',
        'Mantenido': 'Mantido',
        'Sostenido': 'Sustentado',
        'Soportado': 'Suportado',
        'Respaldado': 'Apoiado',
        'Apoyado': 'Apoiado',
        'Ayudado': 'Ajudado',
        'Asistido': 'Assistido',
        'Acompañado': 'Acompanhado',
        'Guiado': 'Guiado',
        'Dirigido': 'Dirigido',
        'Orientado': 'Orientado',
        'Enfocado': 'Focado',
        'Centrado': 'Centrado',
        'Concentrado': 'Concentrado',
        'Dedicado': 'Dedicado',
        'Especializado': 'Especializado',
        'Experto': 'Especialista',
        'Profesional': 'Profissional',
        'Cualificado': 'Qualificado',
        'Capacitado': 'Capacitado',
        'Preparado': 'Preparado',
        'Listo': 'Pronto',
        'Dispuesto': 'Disposto',
        'Disponible': 'Disponível',
        'Accesible': 'Acessível',
        'Alcanzable': 'Alcançável',
        'Obtenible': 'Obtenível',
        'Conseguible': 'Conseguível',
        'Realizable': 'Realizável',
        'Factible': 'Factível',
        'Posible': 'Possível',
        'Probable': 'Provável',
        'Seguro': 'Certo',
        'Cierto': 'Certo',
        'Verdadero': 'Verdadeiro',
        'Real': 'Real',
        'Auténtico': 'Autêntico',
        'Genuino': 'Genuíno',
        'Legítimo': 'Legítimo',
        'Válido': 'Válido',
        'Correcto': 'Correto',
        'Exacto': 'Exato',
        'Preciso': 'Preciso',
        'Puntual': 'Pontual',
        'Oportuno': 'Oportuno',
        'Adecuado': 'Adequado',
        'Apropiado': 'Apropriado',
        'Conveniente': 'Conveniente',
        'Favorable': 'Favorável',
        'Beneficioso': 'Benéfico',
        'Ventajoso': 'Vantajoso',
        'Provechoso': 'Proveitoso',
        'Útil': 'Útil',
        'Valioso': 'Valioso',
        'Importante': 'Importante',
        'Significativo': 'Significativo',
        'Relevante': 'Relevante',
        'Esencial': 'Essencial',
        'Fundamental': 'Fundamental',
        'Básico': 'Básico',
        'Principal': 'Principal',
        'Primario': 'Primário',
        'Secundario': 'Secundário',
        'Auxiliar': 'Auxiliar',
        'Complementario': 'Complementar',
        'Adicional': 'Adicional',
        'Extra': 'Extra',
        'Suplementario': 'Suplementar',
        'Opcional': 'Opcional',
        'Alternativo': 'Alternativo',
        'Sustituto': 'Substituto',
        'Reemplazo': 'Substituição',
        'Cambio': 'Mudança',
        'Intercambio': 'Intercâmbio',
        'Trueque': 'Troca',
        'Permuta': 'Permuta',
        'Rotación': 'Rotação',
        'Turno': 'Turno',
        'Vez': 'Vez',
        'Ocasión': 'Ocasião',
        'Oportunidad': 'Oportunidade',
        'Chance': 'Hipótese',
        'Posibilidad': 'Possibilidade',
        'Probabilidad': 'Probabilidade',
        'Riesgo': 'Risco',
        'Peligro': 'Perigo',
        'Amenaza': 'Ameaça',
        'Advertencia': 'Advertência',
        'Aviso': 'Aviso',
        'Alerta': 'Alerta',
        'Señal': 'Sinal',
        'Indicación': 'Indicação',
        'Muestra': 'Amostra',
        'Ejemplo': 'Exemplo',
        'Modelo': 'Modelo',
        'Patrón': 'Padrão',
        'Plantilla': 'Modelo',
        'Formato': 'Formato',
        'Estilo': 'Estilo',
        'Diseño': 'Design',
        'Aspecto': 'Aspeto',
        'Apariencia': 'Aparência',
        'Imagen': 'Imagem',
        'Figura': 'Figura',
        'Forma': 'Forma',
        'Silueta': 'Silhueta',
        'Contorno': 'Contorno',
        'Perfil': 'Perfil',
        'Línea': 'Linha',
        'Trazo': 'Traço',
        'Marca': 'Marca',
        'Señal': 'Sinal',
        'Signo': 'Signo',
        'Símbolo': 'Símbolo',
        'Icono': 'Ícone',
        'Logo': 'Logótipo',
        'Logotipo': 'Logótipo',
        'Emblema': 'Emblema',
        'Escudo': 'Escudo',
        'Insignia': 'Insígnia',
        'Distintivo': 'Distintivo',
        'Etiqueta': 'Etiqueta',
        'Rótulo': 'Rótulo',
        'Título': 'Título',
        'Nombre': 'Nome',
        'Denominación': 'Denominação',
        'Designación': 'Designação',
        'Calificación': 'Qualificação',
        'Clasificación': 'Classificação',
        'Categorización': 'Categorização',
        'Agrupación': 'Agrupamento',
        'División': 'Divisão',
        'Separación': 'Separação',
        'Distinción': 'Distinção',
        'Diferenciación': 'Diferenciação',
        'Discriminación': 'Discriminação',
        'Selección': 'Seleção',
        'Elección': 'Eleição',
        'Opción': 'Opção',
        'Alternativa': 'Alternativa',
        'Variante': 'Variante',
        'Versión': 'Versão',
        'Edición': 'Edição',
        'Revisión': 'Revisão',
        'Actualización': 'Atualização',
        'Mejora': 'Melhoria',
        'Perfeccionamiento': 'Aperfeiçoamento',
        'Optimización': 'Otimização',
        'Refinamiento': 'Refinamento',
        'Pulimiento': 'Polimento',
        'Acabado': 'Acabamento',
        'Terminación': 'Terminação',
        'Finalización': 'Finalização',
        'Conclusión': 'Conclusão',
        'Cierre': 'Fecho',
        'Clausura': 'Clausura',
        'Término': 'Término',
        'Final': 'Final',
        'Fin': 'Fim',
        'Límite': 'Limite',
        'Frontera': 'Fronteira',
        'Borde': 'Borda',
        'Margen': 'Margem',
        'Orilla': 'Margem',
        'Extremo': 'Extremo',
        'Punta': 'Ponta',
        'Cabo': 'Cabo',
        'Cola': 'Cauda',
        'Rabo': 'Rabo',
        'Apéndice': 'Apêndice',
        'Extensión': 'Extensão',
        'Prolongación': 'Prolongamento',
        'Continuación': 'Continuação',
        'Seguimiento': 'Seguimento',
        'Persecución': 'Perseguição',
        'Búsqueda': 'Busca',
        'Investigación': 'Investigação',
        'Estudio': 'Estudo',
        'Análisis': 'Análise',
        'Examen': 'Exame',
        'Inspección': 'Inspeção',
        'Revisión': 'Revisão',
        'Verificación': 'Verificação',
        'Comprobación': 'Comprovação',
        'Confirmación': 'Confirmação',
        'Validación': 'Validação',
        'Certificación': 'Certificação',
        'Acreditación': 'Acreditação',
        'Autorización': 'Autorização',
        'Permiso': 'Permissão',
        'Licencia': 'Licença',
        'Patente': 'Patente',
        'Registro': 'Registo',
        'Inscripción': 'Inscrição',
        'Matrícula': 'Matrícula',
        'Documentación': 'Documentação',
        'Papeles': 'Papéis',
        'Documentos': 'Documentos',
        'Archivos': 'Arquivos',
        'Expedientes': 'Expedientes',
        'Registros': 'Registos',
        'Datos': 'Dados',
        'Información': 'Informação',
        'Detalles': 'Detalhes',
        'Especificaciones': 'Especificações',
        'Características': 'Características',
        'Propiedades': 'Propriedades',
        'Cualidades': 'Qualidades',
        'Atributos': 'Atributos',
        'Rasgos': 'Traços',
        'Aspectos': 'Aspetos',
        'Elementos': 'Elementos',
        'Componentes': 'Componentes',
        'Partes': 'Partes',
        'Piezas': 'Peças',
        'Fragmentos': 'Fragmentos',
        'Trozos': 'Pedaços',
        'Pedazos': 'Pedaços',
        'Porciones': 'Porções',
        'Secciones': 'Secções',
        'Segmentos': 'Segmentos',
        'Divisiones': 'Divisões',
        'Departamentos': 'Departamentos',
        'Áreas': 'Áreas',
        'Zonas': 'Zonas',
        'Regiones': 'Regiões',
        'Territorios': 'Territórios',
        'Espacios': 'Espaços',
        'Lugares': 'Lugares',
        'Sitios': 'Sítios',
        'Ubicaciones': 'Localizações',
        'Posiciones': 'Posições',
        'Puntos': 'Pontos',
        'Coordenadas': 'Coordenadas',
        'Direcciones': 'Direções',
        'Orientaciones': 'Orientações',
        'Rumbos': 'Rumos',
        'Destinos': 'Destinos',
        'Objetivos': 'Objetivos',
        'Metas': 'Metas',
        'Propósitos': 'Propósitos',
        'Fines': 'Fins',
        'Intenciones': 'Intenções',
        'Planes': 'Planos',
        'Proyectos': 'Projetos',
        'Programas': 'Programas',
        'Esquemas': 'Esquemas',
        'Sistemas': 'Sistemas',
        'Métodos': 'Métodos',
        'Procedimientos': 'Procedimentos',
        'Procesos': 'Processos',
        'Técnicas': 'Técnicas',
        'Estrategias': 'Estratégias',
        'Tácticas': 'Táticas',
        'Enfoques': 'Abordagens',
        'Aproximaciones': 'Aproximações',
        'Acercamientos': 'Aproximações',
        'Contactos': 'Contactos',
        'Conexiones': 'Ligações',
        'Enlaces': 'Ligações',
        'Vínculos': 'Vínculos',
        'Relaciones': 'Relações',
        'Asociaciones': 'Associações',
        'Alianzas': 'Alianças',
        'Sociedades': 'Sociedades',
        'Compañías': 'Companhias',
        'Empresas': 'Empresas',
        'Organizaciones': 'Organizações',
        'Instituciones': 'Instituições',
        'Entidades': 'Entidades',
        'Organismos': 'Organismos',
        'Corporaciones': 'Corporações',
        'Firmas': 'Firmas',
        'Marcas': 'Marcas',
        'Nombres': 'Nomes',
        'Títulos': 'Títulos',
        'Denominaciones': 'Denominações',
        'Designaciones': 'Designações',
        'Calificaciones': 'Qualificações',
        'Clasificaciones': 'Classificações',
        'Categorías': 'Categorias',
        'Tipos': 'Tipos',
        'Clases': 'Classes',
        'Grupos': 'Grupos',
        'Familias': 'Famílias',
        'Géneros': 'Géneros',
        'Especies': 'Espécies',
        'Variedades': 'Variedades',
        'Modalidades': 'Modalidades',
        'Formas': 'Formas',
        'Maneras': 'Maneiras',
        'Modos': 'Modos',
        'Estilos': 'Estilos',
        'Tendencias': 'Tendências',
        'Modas': 'Modas',
        'Corrientes': 'Correntes',
        'Movimientos': 'Movimentos',
        'Flujos': 'Fluxos',
        'Circulaciones': 'Circulações',
        'Transportes': 'Transportes',
        'Traslados': 'Traslados',
        'Desplazamientos': 'Deslocamentos',
        'Movimientos': 'Movimentos',
        'Acciones': 'Ações',
        'Actividades': 'Atividades',
        'Operaciones': 'Operações',
        'Funciones': 'Funções',
        'Tareas': 'Tarefas',
        'Trabajos': 'Trabalhos',
        'Labores': 'Labores',
        'Ocupaciones': 'Ocupações',
        'Empleos': 'Empregos',
        'Puestos': 'Postos',
        'Cargos': 'Cargos',
        'Responsabilidades': 'Responsabilidades',
        'Deberes': 'Deveres',
        'Obligaciones': 'Obrigações',
        'Compromisos': 'Compromissos',
        'Acuerdos': 'Acordos',
        'Contratos': 'Contratos',
        'Convenios': 'Convénios',
        'Pactos': 'Pactos',
        'Tratados': 'Tratados',
        'Alianzas': 'Alianças',
        'Coaliciones': 'Coligações',
        'Uniones': 'Uniões',
        'Federaciones': 'Federações',
        'Confederaciones': 'Confederações',
        'Asociaciones': 'Associações',
        'Agrupaciones': 'Agrupamentos',
        'Congregaciones': 'Congregações',
        'Reuniones': 'Reuniões',
        'Encuentros': 'Encontros',
        'Citas': 'Encontros',
        'Entrevistas': 'Entrevistas',
        'Conversaciones': 'Conversas',
        'Diálogos': 'Diálogos',
        'Charlas': 'Conversas',
        'Conferencias': 'Conferências',
        'Presentaciones': 'Apresentações',
        'Exposiciones': 'Exposições',
        'Demostraciones': 'Demonstrações',
        'Exhibiciones': 'Exibições',
        'Muestras': 'Amostras',
        'Ejemplos': 'Exemplos',
        'Ilustraciones': 'Ilustrações',
        'Representaciones': 'Representações',
        'Imágenes': 'Imagens',
        'Figuras': 'Figuras',
        'Dibujos': 'Desenhos',
        'Esquemas': 'Esquemas',
        'Diagramas': 'Diagramas',
        'Gráficos': 'Gráficos',
        'Tablas': 'Tabelas',
        'Cuadros': 'Quadros',
        'Listas': 'Listas',
        'Catálogos': 'Catálogos',
        'Inventarios': 'Inventários',
        'Índices': 'Índices',
        'Directorios': 'Diretórios',
        'Guías': 'Guias',
        'Manuales': 'Manuais',
        'Instrucciones': 'Instruções',
        'Indicaciones': 'Indicações',
        'Orientaciones': 'Orientações',
        'Consejos': 'Conselhos',
        'Recomendaciones': 'Recomendações',
        'Sugerencias': 'Sugestões',
        'Propuestas': 'Propostas',
        'Ofertas': 'Ofertas',
        'Promociones': 'Promoções',
        'Descuentos': 'Descontos',
        'Rebajas': 'Reduções',
        'Ofertas': 'Ofertas',
        'Gangas': 'Pechinchas',
        'Oportunidades': 'Oportunidades',
        'Ventajas': 'Vantagens',
        'Beneficios': 'Benefícios',
        'Provechos': 'Proveitos',
        'Ganancias': 'Ganhos',
        'Utilidades': 'Utilidades',
        'Rendimientos': 'Rendimentos',
        'Resultados': 'Resultados',
        'Consecuencias': 'Consequências',
        'Efectos': 'Efeitos',
        'Impactos': 'Impactos',
        'Influencias': 'Influências',
        'Repercusiones': 'Repercussões',
        'Implicaciones': 'Implicações',
        'Significados': 'Significados',
        'Sentidos': 'Sentidos',
        'Interpretaciones': 'Interpretações',
        'Explicaciones': 'Explicações',
        'Aclaraciones': 'Esclarecimentos',
        'Definiciones': 'Definições',
        'Conceptos': 'Conceitos',
        'Ideas': 'Ideias',
        'Pensamientos': 'Pensamentos',
        'Reflexiones': 'Reflexões',
        'Consideraciones': 'Considerações',
        'Observaciones': 'Observações',
        'Comentarios': 'Comentários',
        'Opiniones': 'Opiniões',
        'Puntos de vista': 'Pontos de vista',
        'Perspectivas': 'Perspetivas',
        'Enfoques': 'Abordagens',
        'Visiones': 'Visões',
        'Concepciones': 'Conceções',
        'Nociones': 'Noções',
        'Impresiones': 'Impressões',
        'Sensaciones': 'Sensações',
        'Percepciones': 'Perceções',
        'Experiencias': 'Experiências',
        'Vivencias': 'Vivências',
        'Aventuras': 'Aventuras',
        'Viajes': 'Viagens',
        'Excursiones': 'Excursões',
        'Paseos': 'Passeios',
        'Recorridos': 'Percursos',
        'Rutas': 'Rotas',
        'Caminos': 'Caminhos',
        'Senderos': 'Trilhos',
        'Vías': 'Vias',
        'Carreteras': 'Estradas',
        'Calles': 'Ruas',
        'Avenidas': 'Avenidas',
        'Plazas': 'Praças',
        'Parques': 'Parques',
        'Jardines': 'Jardins',
        'Espacios': 'Espaços',
        'Áreas': 'Áreas',
        'Terrenos': 'Terrenos',
        'Campos': 'Campos',
        'Tierras': 'Terras',
        'Suelos': 'Solos',
        'Superficies': 'Superfícies',
        'Pisos': 'Pisos',
        'Plantas': 'Plantas',
        'Niveles': 'Níveis',
        'Alturas': 'Alturas',
        'Elevaciones': 'Elevações',
        'Montañas': 'Montanhas',
        'Colinas': 'Colinas',
        'Valles': 'Vales',
        'Llanuras': 'Planícies',
        'Mesetas': 'Planaltos',
        'Desiertos': 'Desertos',
        'Bosques': 'Florestas',
        'Selvas': 'Selvas',
        'Praderas': 'Pradarias',
        'Pastizales': 'Pastagens',
        'Cultivos': 'Cultivos',
        'Cosechas': 'Colheitas',
        'Productos': 'Produtos',
        'Artículos': 'Artigos',
        'Mercancías': 'Mercadorias',
        'Bienes': 'Bens',
        'Objetos': 'Objetos',
        'Cosas': 'Coisas',
        'Elementos': 'Elementos',
        'Items': 'Itens',
        'Unidades': 'Unidades',
        'Piezas': 'Peças',
        'Componentes': 'Componentes',
        'Partes': 'Partes',
        'Secciones': 'Secções',
        'Divisiones': 'Divisões',
        'Fragmentos': 'Fragmentos',
        'Trozos': 'Pedaços',
        'Porciones': 'Porções',
        'Fracciones': 'Frações',
        'Segmentos': 'Segmentos',
        'Bloques': 'Blocos',
        'Módulos': 'Módulos',
        'Conjuntos': 'Conjuntos',
        'Grupos': 'Grupos',
        'Lotes': 'Lotes',
        'Paquetes': 'Pacotes',
        'Cajas': 'Caixas',
        'Contenedores': 'Contentores',
        'Recipientes': 'Recipientes',
        'Envases': 'Embalagens',
        'Embalajes': 'Embalagens',
        'Paquetes': 'Pacotes',
        'Bultos': 'Volumes',
        'Cargas': 'Cargas',
        'Mercancías': 'Mercadorias',
        'Productos': 'Produtos',
        'Manufacturas': 'Manufaturas',
        'Fabricaciones': 'Fabricações',
        'Producciones': 'Produções',
        'Creaciones': 'Criações',
        'Elaboraciones': 'Elaborações',
        'Construcciones': 'Construções',
        'Edificaciones': 'Edificações',
        'Estructuras': 'Estruturas',
        'Instalaciones': 'Instalações',
        'Establecimientos': 'Estabelecimentos',
        'Locales': 'Locais',
        'Lugares': 'Lugares',
        'Sitios': 'Sítios',
        'Espacios': 'Espaços',
        'Ambientes': 'Ambientes',
        'Atmósferas': 'Atmosferas',
        'Climas': 'Climas',
        'Condiciones': 'Condições',
        'Circunstancias': 'Circunstâncias',
        'Situaciones': 'Situações',
        'Estados': 'Estados',
        'Posiciones': 'Posições',
        'Posturas': 'Posturas',
        'Actitudes': 'Atitudes',
        'Comportamientos': 'Comportamentos',
        'Conductas': 'Condutas',
        'Acciones': 'Ações',
        'Reacciones': 'Reações',
        'Respuestas': 'Respostas',
        'Contestaciones': 'Contestações',
        'Réplicas': 'Réplicas',
        'Devoluciones': 'Devoluções',
        'Retornos': 'Retornos',
        'Regresos': 'Regressos',
        'Vueltas': 'Voltas',
        'Giros': 'Giros',
        'Rotaciones': 'Rotações',
        'Revoluciones': 'Revoluções',
        'Cambios': 'Mudanças',
        'Transformaciones': 'Transformações',
        'Modificaciones': 'Modificações',
        'Alteraciones': 'Alterações',
        'Variaciones': 'Variações',
        'Diferencias': 'Diferenças',
        'Distinciones': 'Distinções',
        'Contrastes': 'Contrastes',
        'Comparaciones': 'Comparações',
        'Similitudes': 'Semelhanças',
        'Parecidos': 'Parecenças',
        'Semejanzas': 'Semelhanças',
        'Analogías': 'Analogias',
        'Correspondencias': 'Correspondências',
        'Equivalencias': 'Equivalências',
        'Igualdades': 'Igualdades',
        'Identidades': 'Identidades',
        'Uniformidades': 'Uniformidades',
        'Homogeneidades': 'Homogeneidades',
        'Consistencias': 'Consistências',
        'Coherencias': 'Coerências',
        'Lógicas': 'Lógicas',
        'Razones': 'Razões',
        'Motivos': 'Motivos',
        'Causas': 'Causas',
        'Orígenes': 'Origens',
        'Fuentes': 'Fontes',
        'Principios': 'Princípios',
        'Bases': 'Bases',
        'Fundamentos': 'Fundamentos',
        'Cimientos': 'Alicerces',
        'Raíces': 'Raízes',
        'Antecedentes': 'Antecedentes',
        'Precedentes': 'Precedentes',
        'Historias': 'Histórias',
        'Pasados': 'Passados',
        'Tradiciones': 'Tradições',
        'Costumbres': 'Costumes',
        'Hábitos': 'Hábitos',
        'Rutinas': 'Rotinas',
        'Prácticas': 'Práticas',
        'Ejercicios': 'Exercícios',
        'Entrenamientos': 'Treinos',
        'Preparaciones': 'Preparações',
        'Formaciones': 'Formações',
        'Educaciones': 'Educações',
        'Enseñanzas': 'Ensinos',
        'Aprendizajes': 'Aprendizagens',
        'Estudios': 'Estudos',
        'Investigaciones': 'Investigações',
        'Análisis': 'Análises',
        'Exámenes': 'Exames',
        'Pruebas': 'Provas',
        'Tests': 'Testes',
        'Evaluaciones': 'Avaliações',
        'Valoraciones': 'Valorizações',
        'Estimaciones': 'Estimativas',
        'Cálculos': 'Cálculos',
        'Mediciones': 'Medições',
        'Medidas': 'Medidas',
        'Dimensiones': 'Dimensões',
        'Tamaños': 'Tamanhos',
        'Magnitudes': 'Magnitudes',
        'Proporciones': 'Proporções',
        'Escalas': 'Escalas',
        'Niveles': 'Níveis',
        'Grados': 'Graus',
        'Intensidades': 'Intensidades',
        'Fuerzas': 'Forças',
        'Potencias': 'Potências',
        'Energías': 'Energias',
        'Poderes': 'Poderes',
        'Capacidades': 'Capacidades',
        'Habilidades': 'Habilidades',
        'Destrezas': 'Destrezas',
        'Competencias': 'Competências',
        'Aptitudes': 'Aptidões',
        'Talentos': 'Talentos',
        'Dones': 'Dons',
        'Cualidades': 'Qualidades',
        'Virtudes': 'Virtudes',
        'Méritos': 'Méritos',
        'Valores': 'Valores',
        'Precios': 'Preços',
        'Costos': 'Custos',
        'Gastos': 'Gastos',
        'Inversiones': 'Investimentos',
        'Compras': 'Compras',
        'Adquisiciones': 'Aquisições',
        'Ventas': 'Vendas',
        'Transacciones': 'Transações',
        'Operaciones': 'Operações',
        'Negocios': 'Negócios',
        'Comercios': 'Comércios',
        'Intercambios': 'Intercâmbios',
        'Trueques': 'Trocas',
        'Permutas': 'Permutas',
        'Cambios': 'Trocas',
        'Sustituciones': 'Substituições',
        'Reemplazos': 'Substituições',
        'Renovaciones': 'Renovações',
        'Actualizaciones': 'Atualizações',
        'Mejoras': 'Melhorias',
        'Perfeccionamientos': 'Aperfeiçoamentos',
        'Optimizaciones': 'Otimizações',
        'Refinamientos': 'Refinamentos',
        'Correcciones': 'Correções',
        'Reparaciones': 'Reparações',
        'Arreglos': 'Arranjos',
        'Ajustes': 'Ajustes',
        'Regulaciones': 'Regulações',
        'Configuraciones': 'Configurações',
        'Programaciones': 'Programações',
        'Planificaciones': 'Planeamentos',
        'Organizaciones': 'Organizações',
        'Estructuraciones': 'Estruturações',
        'Ordenaciones': 'Ordenações',
        'Clasificaciones': 'Classificações',
        'Categorizaciones': 'Categorizações',
        'Agrupaciones': 'Agrupamentos',
        'Divisiones': 'Divisões',
        'Separaciones': 'Separações',
        'Distribuciones': 'Distribuições',
        'Reparticiones': 'Repartições',
        'Asignaciones': 'Atribuições',
        'Designaciones': 'Designações',
        'Nombramientos': 'Nomeações',
        'Elecciones': 'Eleições',
        'Selecciones': 'Seleções',
        'Escogencias': 'Escolhas',
        'Opciones': 'Opções',
        'Alternativas': 'Alternativas',
        'Posibilidades': 'Possibilidades',
        'Oportunidades': 'Oportunidades',
        'Ocasiones': 'Ocasiões',
        'Momentos': 'Momentos',
        'Instantes': 'Instantes',
        'Tiempos': 'Tempos',
        'Períodos': 'Períodos',
        'Épocas': 'Épocas',
        'Eras': 'Eras',
        'Edades': 'Idades',
        'Generaciones': 'Gerações',
        'Décadas': 'Décadas',
        'Siglos': 'Séculos',
        'Milenios': 'Milénios',
        'Años': 'Anos',
        'Meses': 'Meses',
        'Semanas': 'Semanas',
        'Días': 'Dias',
        'Horas': 'Horas',
        'Minutos': 'Minutos',
        'Segundos': 'Segundos',
        'Momentos': 'Momentos',
        'Instantes': 'Instantes',
        'Intervalos': 'Intervalos',
        'Pausas': 'Pausas',
        'Descansos': 'Descansos',
        'Recreos': 'Recreios',
        'Vacaciones': 'Férias',
        'Feriados': 'Feriados',
        'Festivales': 'Festivais',
        'Celebraciones': 'Celebrações',
        'Fiestas': 'Festas',
        'Eventos': 'Eventos',
        'Acontecimientos': 'Acontecimentos',
        'Sucesos': 'Sucessos',
        'Hechos': 'Factos',
        'Realidades': 'Realidades',
        'Verdades': 'Verdades',
        'Certezas': 'Certezas',
        'Seguridades': 'Seguranças',
        'Garantías': 'Garantias',
        'Promesas': 'Promessas',
        'Compromisos': 'Compromissos',
        'Obligaciones': 'Obrigações',
        'Responsabilidades': 'Responsabilidades',
        'Deberes': 'Deveres',
        'Tareas': 'Tarefas',
        'Misiones': 'Missões',
        'Encargos': 'Encargos',
        'Asignaciones': 'Atribuições',
        'Trabajos': 'Trabalhos',
        'Empleos': 'Empregos',
        'Ocupaciones': 'Ocupações',
        'Profesiones': 'Profissões',
        'Oficios': 'Ofícios',
        'Carreras': 'Carreiras',
        'Vocaciones': 'Vocações',
        'Especialidades': 'Especialidades',
        'Disciplinas': 'Disciplinas',
        'Materias': 'Matérias',
        'Asignaturas': 'Disciplinas',
        'Temas': 'Temas',
        'Asuntos': 'Assuntos',
        'Cuestiones': 'Questões',
        'Problemas': 'Problemas',
        'Dificultades': 'Dificuldades',
        'Obstáculos': 'Obstáculos',
        'Impedimentos': 'Impedimentos',
        'Barreras': 'Barreiras',
        'Limitaciones': 'Limitações',
        'Restricciones': 'Restrições',
        'Prohibiciones': 'Proibições',
        'Negaciones': 'Negações',
        'Rechazos': 'Rejeições',
        'Desaprobaciones': 'Desaprovações',
        'Críticas': 'Críticas',
        'Objeciones': 'Objeções',
        'Protestas': 'Protestos',
        'Quejas': 'Queixas',
        'Reclamos': 'Reclamações',
        'Demandas': 'Demandas',
        'Exigencias': 'Exigências',
        'Requisitos': 'Requisitos',
        'Condiciones': 'Condições',
        'Términos': 'Termos',
        'Cláusulas': 'Cláusulas',
        'Artículos': 'Artigos',
        'Secciones': 'Secções',
        'Capítulos': 'Capítulos',
        'Partes': 'Partes',
        'Divisiones': 'Divisões',
        'Subdivisiones': 'Subdivisões',
        'Categorías': 'Categorias',
        'Subcategorías': 'Subcategorias',
        'Tipos': 'Tipos',
        'Subtipos': 'Subtipos',
        'Variedades': 'Variedades',
        'Modalidades': 'Modalidades',
        'Versiones': 'Versões',
        'Ediciones': 'Edições',
        'Revisiones': 'Revisões',
        'Actualizaciones': 'Atualizações',
        'Modificaciones': 'Modificações',
        'Cambios': 'Mudanças',
        'Alteraciones': 'Alterações',
        'Transformaciones': 'Transformações',
        'Conversiones': 'Conversões',
        'Adaptaciones': 'Adaptações',
        'Ajustes': 'Ajustes',
        'Correcciones': 'Correções',
        'Mejoras': 'Melhorias',
        'Perfeccionamientos': 'Aperfeiçoamentos',
        'Optimizaciones': 'Otimizações',
        'Refinamientos': 'Refinamentos',
        'Desarrollos': 'Desenvolvimentos',
        'Evoluciones': 'Evoluções',
        'Progresos': 'Progressos',
        'Avances': 'Avanços',
        'Adelantos': 'Avanços',
        'Innovaciones': 'Inovações',
        'Novedades': 'Novidades',
        'Noticias': 'Notícias',
        'Informaciones': 'Informações',
        'Comunicaciones': 'Comunicações',
        'Mensajes': 'Mensagens',
        'Avisos': 'Avisos',
        'Anuncios': 'Anúncios',
        'Declaraciones': 'Declarações',
        'Pronunciamientos': 'Pronunciamentos',
        'Manifestaciones': 'Manifestações',
        'Expresiones': 'Expressões',
        'Demostraciones': 'Demonstrações',
        'Exhibiciones': 'Exibições',
        'Presentaciones': 'Apresentações',
        'Exposiciones': 'Exposições',
        'Muestras': 'Amostras',
        'Ejemplos': 'Exemplos',
        'Modelos': 'Modelos',
        'Patrones': 'Padrões',
        'Plantillas': 'Modelos',
        'Formatos': 'Formatos',
        'Estructuras': 'Estruturas',
        'Marcos': 'Molduras',
        'Esquemas': 'Esquemas',
        'Diseños': 'Designs',
        'Planos': 'Planos',
        'Proyectos': 'Projetos',
        'Programas': 'Programas',
        'Planes': 'Planos',
        'Estrategias': 'Estratégias',
        'Tácticas': 'Táticas',
        'Métodos': 'Métodos',
        'Sistemas': 'Sistemas',
        'Procedimientos': 'Procedimentos',
        'Procesos': 'Processos',
        'Técnicas': 'Técnicas',
        'Formas': 'Formas',
        'Maneras': 'Maneiras',
        'Modos': 'Modos',
        'Estilos': 'Estilos',
        'Enfoques': 'Abordagens',
        'Aproximaciones': 'Aproximações',
        'Acercamientos': 'Aproximações',
        'Contactos': 'Contactos',
        'Conexiones': 'Ligações',
        'Enlaces': 'Ligações',
        'Vínculos': 'Vínculos',
        'Relaciones': 'Relações',
        'Asociaciones': 'Associações',
        'Alianzas': 'Alianças',
        'Uniones': 'Uniões',
        'Fusiones': 'Fusões',
        'Combinaciones': 'Combinações',
        'Mezclas': 'Misturas',
        'Integraciones': 'Integrações',
        'Incorporaciones': 'Incorporações',
        'Inclusiones': 'Inclusões',
        'Adiciones': 'Adições',
        'Agregaciones': 'Agregações',
        'Sumas': 'Somas',
        'Totales': 'Totais',
        'Conjuntos': 'Conjuntos',
        'Grupos': 'Grupos',
        'Colecciones': 'Coleções',
        'Series': 'Séries',
        'Secuencias': 'Sequências',
        'Sucesiones': 'Sucessões',
        'Cadenas': 'Cadeias',
        'Líneas': 'Linhas',
        'Filas': 'Filas',
        'Columnas': 'Colunas',
        'Hileras': 'Fileiras',
        'Rangos': 'Gamas',
        'Niveles': 'Níveis',
        'Escalones': 'Degraus',
        'Grados': 'Graus',
        'Etapas': 'Etapas',
        'Fases': 'Fases',
        'Períodos': 'Períodos',
        'Ciclos': 'Ciclos',
        'Rondas': 'Rondas',
        'Turnos': 'Turnos',
        'Veces': 'Vezes',
        'Ocasiones': 'Ocasiões',
        'Oportunidades': 'Oportunidades',
        'Posibilidades': 'Possibilidades',
        'Probabilidades': 'Probabilidades',
        'Chances': 'Hipóteses',
        'Riesgos': 'Riscos',
        'Peligros': 'Perigos',
        'Amenazas': 'Ameaças',
        'Advertencias': 'Advertências',
        'Avisos': 'Avisos',
        'Alertas': 'Alertas',
        'Señales': 'Sinais',
        'Indicaciones': 'Indicações',
        'Signos': 'Signos',
        'Síntomas': 'Sintomas',
        'Manifestaciones': 'Manifestações',
        'Evidencias': 'Evidências',
        'Pruebas': 'Provas',
        'Testimonios': 'Testemunhos',
        'Declaraciones': 'Declarações',
        'Afirmaciones': 'Afirmações',
        'Aseveraciones': 'Asserções',
        'Confirmaciones': 'Confirmações',
        'Verificaciones': 'Verificações',
        'Comprobaciones': 'Comprovações',
        'Validaciones': 'Validações',
        'Certificaciones': 'Certificações',
        'Acreditaciones': 'Acreditações',
        'Autorizaciones': 'Autorizações',
        'Permisos': 'Permissões',
        'Licencias': 'Licenças',
        'Patentes': 'Patentes',
        'Registros': 'Registos',
        'Inscripciones': 'Inscrições',
        'Matrículas': 'Matrículas',
        'Documentaciones': 'Documentações',
        'Papeles': 'Papéis',
        'Documentos': 'Documentos',
        'Archivos': 'Arquivos',
        'Expedientes': 'Expedientes',
        'Registros': 'Registos',
        'Datos': 'Dados',
        'Informaciones': 'Informações',
        'Detalles': 'Detalhes',
        'Especificaciones': 'Especificações',
        'Características': 'Características',
        'Propiedades': 'Propriedades',
        'Cualidades': 'Qualidades',
        'Atributos': 'Atributos',
        'Rasgos': 'Traços',
        'Aspectos': 'Aspetos',
        'Elementos': 'Elementos',
        'Componentes': 'Componentes',
        'Partes': 'Partes',
        'Piezas': 'Peças',
        'Fragmentos': 'Fragmentos',
        'Trozos': 'Pedaços',
        'Pedazos': 'Pedaços',
        'Porciones': 'Porções',
        'Secciones': 'Secções',
        'Segmentos': 'Segmentos',
        'Divisiones': 'Divisões',
        'Departamentos': 'Departamentos',
        'Áreas': 'Áreas',
        'Zonas': 'Zonas',
        'Regiones': 'Regiões',
        'Territorios': 'Territórios',
        'Espacios': 'Espaços',
        'Lugares': 'Lugares',
        'Sitios': 'Sítios',
        'Ubicaciones': 'Localizações',
        'Posiciones': 'Posições',
        'Puntos': 'Pontos',
        'Coordenadas': 'Coordenadas',
        'Direcciones': 'Direções',
        'Orientaciones': 'Orientações',
        'Rumbos': 'Rumos',
        'Destinos': 'Destinos',
        'Objetivos': 'Objetivos',
        'Metas': 'Metas',
        'Propósitos': 'Propósitos',
        'Fines': 'Fins',
        'Intenciones': 'Intenções',
        'Planes': 'Planos',
        'Proyectos': 'Projetos',
        'Programas': 'Programas',
        'Esquemas': 'Esquemas',
        'Sistemas': 'Sistemas',
        'Métodos': 'Métodos',
        'Procedimientos': 'Procedimentos',
        'Procesos': 'Processos',
        'Técnicas': 'Técnicas',
        'Estrategias': 'Estratégias',
        'Tácticas': 'Táticas',
        'Enfoques': 'Abordagens',
        'Aproximaciones': 'Aproximações',
        'Acercamientos': 'Aproximações'
    };
    
    let translatedText = text;
    
    // Aplicar traduções
    for (const [spanish, portuguese] of Object.entries(translations)) {
        const regex = new RegExp(`\\b${spanish}\\b`, 'gi');
        translatedText = translatedText.replace(regex, portuguese);
    }
    
    return translatedText;
}

// Função para normalizar marca (primeira letra maiúscula, resto minúsculo)
function normalizeBrand(brand) {
    if (!brand || typeof brand !== 'string') return '';
    
    // Converter para primeira letra maiúscula, resto minúsculo
    return brand.charAt(0).toUpperCase() + brand.slice(1).toLowerCase();
}

// Função para converter EAN de notação científica para número completo
function formatEAN(eanValue) {
    if (!eanValue) return '';
    
    // Converter para string se for número
    let eanStr = String(eanValue);
    
    // Se contém notação científica (E+ ou e+)
    if (eanStr.includes('E+') || eanStr.includes('e+')) {
        try {
            // Converter para número e depois para string sem notação científica
            const num = parseFloat(eanStr);
            // Usar toFixed(0) para remover decimais e notação científica
            eanStr = num.toFixed(0);
        } catch (error) {
            console.log(`⚠️ Erro ao converter EAN: ${eanValue}`);
            return eanValue;
        }
    }
    
    // Remover vírgulas se existirem
    eanStr = eanStr.replace(/,/g, '');
    
    return eanStr;
}

// Função para processar imagens extras
function processExtraImages(extraImagesJson) {
    if (!extraImagesJson || typeof extraImagesJson !== 'string') {
        return [];
    }
    
    // Verificar se é JSON válido
    if (!extraImagesJson.trim().startsWith('{') && !extraImagesJson.trim().startsWith('[')) {
        return [];
    }
    
    try {
        const parsed = JSON.parse(extraImagesJson);
        
        // Se for objeto com propriedade details
        if (parsed && typeof parsed === 'object' && parsed.details && Array.isArray(parsed.details)) {
            const validImages = parsed.details.filter(url => 
                url && 
                typeof url === 'string' && 
                !url.includes('_thumb') &&
                (url.startsWith('http') || url.startsWith('https'))
            );
            return validImages;
        }
        
        // Se for array direto
        if (Array.isArray(parsed)) {
            const validImages = parsed.filter(url => 
                url && 
                typeof url === 'string' && 
                !url.includes('_thumb') &&
                (url.startsWith('http') || url.startsWith('https'))
            );
            return validImages;
        }
        
    } catch (error) {
        // Silenciar erros de JSON para não poluir logs
    }
    
    return [];
}

// Função principal para transformar produto
function transformProduct(visiProduct) {
    try {
        // Dados básicos
        const name = visiProduct.name || '';
        const brand = normalizeBrand(visiProduct.brand || ''); // CORREÇÃO 3: Normalizar marca
        
        // CORREÇÃO 5: Usar short_description se disponível, senão usar name
        const title = visiProduct.short_description && visiProduct.short_description.trim() !== '' 
            ? translateText(visiProduct.short_description) 
            : translateText(name);
            
        const description = translateText(visiProduct.description || '');
        const specifications = translateText(visiProduct.specifications || '');
        const content = translateText(visiProduct.content || '');
        
        // CORREÇÃO 4: Combinar descrição + especificações técnicas
        let fullDescription = description;
        if (specifications && specifications.trim() !== '') {
            fullDescription += specifications.trim() !== '' ? `\n\n<h3>Especificações Técnicas</h3>\n${specifications}` : '';
        }
        
        // Preços
        const basePrice = parseFloat(visiProduct.precio_venta_cliente_final) || 0;
        const priceWithVAT = basePrice > 0 ? (basePrice * 1.23).toFixed(2) : '1.00'; // CORREÇÃO 5: Fallback para 1.00
        const comparePrice = parseFloat(visiProduct.PVP) || 0;
        const costPrice = parseFloat(visiProduct.precio_neto_compra) || 0;
        
        // CORREÇÃO 2: Stock alto = 10 (não 100)
        const stockLevel = visiProduct.stock || 'low';
        const inventoryQty = stockLevel === 'high' ? 10 : stockLevel === 'medium' ? 5 : 1;
        
        // Categoria e tags
        const category = translateText(visiProduct.category || '');
        const categoryParent = translateText(visiProduct.category_parent || '');
        
        // CORREÇÃO 3 e 5: Tags com marca normalizada e categoria
        const tags = [brand, category, categoryParent].filter(tag => tag && tag.trim() !== '').join(', ');
        
        // Status
        const published = visiProduct.published === '1' ? 'active' : 'draft';
        const status = published;
        
        // Imagem principal
        const mainImage = visiProduct.image_path || '';
        
        // CORREÇÃO 6: EAN formatado corretamente
        const eanFormatted = formatEAN(visiProduct.ean);
        
        // Handle único
        const handle = name.toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-')
            .replace(/^-|-$/g, '');
        
        // Produto base
        const baseProduct = {
            'Handle': handle,
            'Title': title,
            'Body (HTML)': fullDescription, // CORREÇÃO 4: Descrição + especificações
            'Vendor': brand, // CORREÇÃO 3: Marca normalizada
            'Product Category': '',
            'Type': category,
            'Tags': tags, // CORREÇÃO 3 e 5: Tags completas
            'Published': 'TRUE',
            'Option1 Name': '',
            'Option1 Value': '',
            'Option2 Name': '',
            'Option2 Value': '',
            'Option3 Name': '',
            'Option3 Value': '',
            'Variant SKU': visiProduct.name,
            'Variant Grams': '',
            'Variant Inventory Tracker': 'shopify',
            'Variant Inventory Qty': inventoryQty, // CORREÇÃO 2: Stock correto
            'Variant Inventory Policy': 'deny',
            'Variant Fulfillment Service': 'manual',
            'Variant Price': priceWithVAT,
            'Variant Compare At Price': comparePrice > 0 ? comparePrice.toFixed(2) : '',
            'Variant Requires Shipping': 'TRUE',
            'Variant Taxable': 'TRUE',
            'Variant Barcode': eanFormatted, // CORREÇÃO 6: EAN formatado
            'Image Src': mainImage,
            'Image Position': '1',
            'Image Alt Text': title,
            'Gift Card': 'FALSE',
            'SEO Title': `${title} | ${brand}`,
            'SEO Description': translateText(visiProduct.short_description || ''),
            'Google Shopping / Google Product Category': '',
            'Google Shopping / Gender': '',
            'Google Shopping / Age Group': '',
            'Google Shopping / MPN': visiProduct.name,
            'Google Shopping / Condition': 'new',
            'Google Shopping / Custom Product': 'TRUE',
            'Variant Image': '',
            'Variant Weight Unit': 'g',
            'Variant Tax Code': '',
            'Cost per item': costPrice > 0 ? costPrice.toFixed(2) : '',
            'Included / United States': 'TRUE',
            'Price / United States': '',
            'Compare At Price / United States': '',
            'Included / International': 'TRUE',
            'Price / International': '',
            'Compare At Price / International': '',
            'Status': status
        };
        
        // Array de produtos (produto base + imagens extras)
        const products = [baseProduct];
        
        // CORREÇÃO 1: Adicionar linhas para imagens extras
        const extraImages = processExtraImages(visiProduct.extra_images_paths);
        
        extraImages.forEach((imageUrl, index) => {
            const extraImageProduct = {
                'Handle': handle,
                'Title': '',
                'Body (HTML)': '',
                'Vendor': '',
                'Product Category': '',
                'Type': '',
                'Tags': '',
                'Published': '',
                'Option1 Name': '',
                'Option1 Value': '',
                'Option2 Name': '',
                'Option2 Value': '',
                'Option3 Name': '',
                'Option3 Value': '',
                'Variant SKU': '',
                'Variant Grams': '',
                'Variant Inventory Tracker': '',
                'Variant Inventory Qty': '',
                'Variant Inventory Policy': '',
                'Variant Fulfillment Service': '',
                'Variant Price': '',
                'Variant Compare At Price': '',
                'Variant Requires Shipping': '',
                'Variant Taxable': '',
                'Variant Barcode': '',
                'Image Src': imageUrl,
                'Image Position': (index + 2).toString(),
                'Image Alt Text': title,
                'Gift Card': '',
                'SEO Title': '',
                'SEO Description': '',
                'Google Shopping / Google Product Category': '',
                'Google Shopping / Gender': '',
                'Google Shopping / Age Group': '',
                'Google Shopping / MPN': '',
                'Google Shopping / Condition': '',
                'Google Shopping / Custom Product': '',
                'Variant Image': '',
                'Variant Weight Unit': '',
                'Variant Tax Code': '',
                'Cost per item': '',
                'Included / United States': '',
                'Price / United States': '',
                'Compare At Price / United States': '',
                'Included / International': '',
                'Price / International': '',
                'Compare At Price / International': '',
                'Status': ''
            };
            
            products.push(extraImageProduct);
        });
        
        return products;
        
    } catch (error) {
        console.error('Erro ao transformar produto:', visiProduct.name, error.message);
        return null;
    }
}

// Função principal
function transformVisiCSVToShopify(inputPath, outputPath) {
    try {
        console.log('🚀 Iniciando transformação CSV Visiotech → Shopify...');
        console.log(`📁 Ficheiro entrada: ${inputPath}`);
        console.log(`📁 Ficheiro saída: ${outputPath}`);
        
        // Ler CSV original
        const csvContent = fs.readFileSync(inputPath, 'utf-8');
        const lines = csvContent.split('\n').filter(line => line.trim());
        
        if (lines.length === 0) {
            throw new Error('CSV vazio');
        }
        
        console.log(`📄 ${lines.length} linhas encontradas`);
        
        // Headers do CSV original
        const headers = lines[0].split(';');
        console.log(`📋 ${headers.length} colunas encontradas`);
        
        // Headers do CSV Shopify
        const shopifyHeaders = [
            'Handle', 'Title', 'Body (HTML)', 'Vendor', 'Product Category', 'Type', 'Tags', 'Published',
            'Option1 Name', 'Option1 Value', 'Option2 Name', 'Option2 Value', 'Option3 Name', 'Option3 Value',
            'Variant SKU', 'Variant Grams', 'Variant Inventory Tracker', 'Variant Inventory Qty',
            'Variant Inventory Policy', 'Variant Fulfillment Service', 'Variant Price', 'Variant Compare At Price',
            'Variant Requires Shipping', 'Variant Taxable', 'Variant Barcode', 'Image Src', 'Image Position',
            'Image Alt Text', 'Gift Card', 'SEO Title', 'SEO Description', 'Google Shopping / Google Product Category',
            'Google Shopping / Gender', 'Google Shopping / Age Group', 'Google Shopping / MPN',
            'Google Shopping / Condition', 'Google Shopping / Custom Product', 'Variant Image',
            'Variant Weight Unit', 'Variant Tax Code', 'Cost per item', 'Included / United States',
            'Price / United States', 'Compare At Price / United States', 'Included / International',
            'Price / International', 'Compare At Price / International', 'Status'
        ];
        
        // Processar produtos
        const allShopifyProducts = [];
        let processedCount = 0;
        let errorCount = 0;
        
        for (let i = 1; i < lines.length; i++) {
            try {
                const values = lines[i].split(';');
                
                if (values.length !== headers.length) {
                    console.log(`⚠️ Linha ${i}: ${values.length} valores vs ${headers.length} headers`);
                    continue;
                }
                
                // Criar objeto produto
                const visiProduct = {};
                headers.forEach((header, index) => {
                    visiProduct[header] = values[index] || '';
                });
                
                // Transformar produto
                const shopifyProducts = transformProduct(visiProduct);
                
                if (shopifyProducts && Array.isArray(shopifyProducts)) {
                    allShopifyProducts.push(...shopifyProducts);
                    processedCount++;
                    
                    if (processedCount % 100 === 0) {
                        console.log(`📦 Produtos processados: ${processedCount}`);
                    }
                } else {
                    errorCount++;
                }
                
            } catch (error) {
                console.error(`❌ Erro na linha ${i}:`, error.message);
                errorCount++;
            }
        }
        
        console.log(`✅ Processamento concluído:`);
        console.log(`   • Produtos processados: ${processedCount}`);
        console.log(`   • Erros: ${errorCount}`);
        console.log(`   • Total linhas Shopify: ${allShopifyProducts.length}`);
        
        // Gerar CSV Shopify
        console.log('📝 Gerando CSV Shopify...');
        
        const csvLines = [shopifyHeaders.join(',')];
        
        allShopifyProducts.forEach(product => {
            const values = shopifyHeaders.map(header => {
                const value = product[header] || '';
                // Escapar vírgulas e aspas
                if (value.includes(',') || value.includes('"') || value.includes('\n')) {
                    return `"${value.replace(/"/g, '""')}"`;
                }
                return value;
            });
            csvLines.push(values.join(','));
        });
        
        // Escrever ficheiro
        fs.writeFileSync(outputPath, csvLines.join('\n'), 'utf-8');
        
        console.log(`🎉 CSV Shopify gerado com sucesso!`);
        console.log(`📊 ${csvLines.length - 1} linhas de produtos`);
        console.log(`📁 Ficheiro: ${outputPath}`);
        
        return {
            processed: processedCount,
            errors: errorCount,
            shopifyLines: csvLines.length - 1
        };
        
    } catch (error) {
        console.error('🚨 Erro na transformação:', error.message);
        throw error;
    }
}

module.exports = {
    transformVisiCSVToShopify,
    transformProduct,
    translateText,
    processExtraImages,
    normalizeBrand,
    formatEAN
};

